language: node_js
node_js:
 - "node"

cache: yarn

jobs:
  include:
    - script: yarn test:unit
    - stage: deploy
      before_script: "curl -H \"X-Auth-Token: $FOOTBALL_DATA_TOKEN\" -X GET http://api.football-data.org/v2/competitions/2017/matches?status=FINISHED > ./src/json/primeiraLiga.json && cat ./src/json/primeiraLiga.json"
    - before_script: "curl -H \"X-Auth-Token: $FOOTBALL_DATA_TOKEN\" -X GET http://api.football-data.org/v2/competitions/2021/matches?status=FINISHED > ./src/json/premierLeague.json && cat ./src/json/primeiraLiga.json"
      script: yarn build
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist
        token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: main