language: node_js
node_js:
 - "node"

cache: yarn

script:
 - "./build.sh $FOOTBALL_DATA_TOKEN"

deploy:
 provider: pages
 skip_cleanup: true
 local_dir: dist
 token: $GITHUB_TOKEN
 keep_history: true
 on:
   branch: main