language: node_js
node_js:
 - 16

cache: yarn

before_install:
  - sudo apt-get update
  - sudo apt-get install python3

script: yarn test:unit

jobs:
  include:
    - stage: deploy
      script:
        - "curl -H \"X-Auth-Token: $FOOTBALL_DATA_TOKEN\" -X GET http://api.football-data.org/v2/competitions/2017/matches?status=FINISHED > ./src/json/primeiraLiga.json"
        - "curl -H \"X-Auth-Token: $FOOTBALL_DATA_TOKEN\" -X GET http://api.football-data.org/v2/competitions/2021/matches?status=FINISHED > ./src/json/premierLeague.json"
        - "yarn build"
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist
        token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: main
