language: node_js
node_js:
 - "node"

cache: yarn

script:
 - "curl -H \"X-Auth-Token: $FOOTBALL_DATA_TOKEN\" -X GET http://api.football-data.org/v2/competitions/2017/matches > ./src/json/primeiraLiga.json && yarn build"

deploy:
 provider: pages
 skip_cleanup: true
 local_dir: dist
 token: $GITHUB_TOKEN
 keep_history: true
 on:
   branch: main