name: pages-build-deployment

on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '45 1 * * *'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm run test:unit

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: python fixtures.py -c 2017 -s 2022 -p ./src/json/primeira-liga.json
        env:
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}

      - run: python fixtures.py -c 2021 -s 2022 -p ./src/json/premier-league.json
        env:
          FOOTBALL_DATA_TOKEN: ${{ secrets.FOOTBALL_DATA_TOKEN }}

      - run: npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v2
